# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches:
      - master
    paths:
      - version.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: unshallow
        run: git fetch --unshallow
      - name: echoHead
        run: echo "$(git rev-parse HEAD)"
      - name: echoRev
        run: echo "$(git rev-parse --abbrev-ref HEAD)" 
  allgood:
    name: Type 2
    runs-on: ubuntu-latest
    needs: [build]
